# install_startup_task.ps1
# ============================================================
# Behaviour:
#   - Fires once when you open / unlock / wake the laptop
#   - Runs at most once per day — if it already ran today it skips
#   - Hard-killed after 20 minutes no matter what
#   - Below-normal CPU priority — won't compete with your work
#   - No window, no terminal flash, completely silent
#   - Sends a desktop notification when done
#
# Run ONCE in PowerShell (as Administrator):
#   Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
#   .\install_startup_task.ps1
#
# Optional: change the folder path if job_scraper is not on the Desktop
#   .\install_startup_task.ps1 -ScraperDir "C:\path\to\job_scraper"
# ============================================================

param(
    [string]$ScraperDir = "$env:USERPROFILE\Desktop\job_scraper"
)

$TaskName    = "JobScraper_Ashour"
$WrapperPath = Join-Path $ScraperDir "run_once_today.ps1"   # cooldown wrapper
$ScriptPath  = Join-Path $ScraperDir "main.py"
$LogPath     = Join-Path $ScraperDir "scraper.log"

# ── Detect Python: prefer venv inside the project, then global ───────────────
$VenvPython = Join-Path $ScraperDir "venv\Scripts\python.exe"
$PythonExe  = if (Test-Path $VenvPython) {
                  $VenvPython
              } else {
                  (Get-Command python -ErrorAction SilentlyContinue).Source
              }

if (-not $PythonExe) {
    Write-Error "Python not found. Create the venv first (see README), then re-run."
    exit 1
}
if (-not (Test-Path $ScriptPath)) {
    Write-Error "main.py not found at $ScriptPath. Check -ScraperDir."
    exit 1
}

# ── Write the cooldown wrapper script ────────────────────────────────────────
# This wrapper is what Task Scheduler actually calls.
# It checks a stamp file — if the scraper already ran today it exits immediately,
# so unlocking your screen mid-day or waking from sleep does NOT re-fire it.
$WrapperContent = @"
# run_once_today.ps1  —  generated by install_startup_task.ps1
# Ensures the scraper runs at most once per calendar day.

`$StampFile  = Join-Path "$ScraperDir" ".last_run_date"
`$PythonExe  = "$PythonExe"
`$ScriptPath = "$ScriptPath"
`$Today      = (Get-Date).ToString("yyyy-MM-dd")

# Read last run date
`$LastRun = ""
if (Test-Path `$StampFile) {
    `$LastRun = (Get-Content `$StampFile -Raw).Trim()
}

# Already ran today — exit silently
if (`$LastRun -eq `$Today) {
    exit 0
}

# Wait 30 seconds for network to come up after wake/login
Start-Sleep -Seconds 30

# Run the scraper
& `$PythonExe `$ScriptPath --quick

# Record today's date as the last run date
`$Today | Set-Content `$StampFile
"@

Set-Content -Path $WrapperPath -Value $WrapperContent -Encoding UTF8
Write-Host "  Wrapper written: $WrapperPath"

# ── Remove existing task ──────────────────────────────────────────────────────
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "  Removed previous task."
}

# ── Action: PowerShell runs the wrapper, hidden ───────────────────────────────
$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$WrapperPath`"" `
    -WorkingDirectory $ScraperDir

# ── Triggers: logon + workstation unlock + wake from sleep ───────────────────
# Together these cover: fresh boot, lid open, screen unlock after lock.
$TriggerLogon  = New-ScheduledTaskTrigger -AtLogOn
$TriggerUnlock = New-CimInstance `
    -Namespace    ROOT\Microsoft\Windows\TaskScheduler `
    -ClassName    MSFT_TaskSessionStateChangeTrigger `
    -ClientOnly `
    -Property @{ StateChange = 8 }   # 8 = workstation unlock

# ── Settings ──────────────────────────────────────────────────────────────────
$Settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit    (New-TimeSpan -Minutes 20) `
    -RunOnlyIfNetworkAvailable                        `
    -MultipleInstances     IgnoreNew                  `
    -Priority              7                          `
    -Hidden

# ── Register ──────────────────────────────────────────────────────────────────
Register-ScheduledTask `
    -TaskName  $TaskName `
    -Action    $Action `
    -Trigger   @($TriggerLogon, $TriggerUnlock) `
    -Settings  $Settings `
    -RunLevel  Limited `
    -Force | Out-Null

Write-Host ""
Write-Host "SUCCESS: Task registered." -ForegroundColor Green
Write-Host ""
Write-Host "  Fires on:    Login, screen unlock, lid open"
Write-Host "  Frequency:   At most once per day — skips if already ran today"
Write-Host "  Max runtime: 20 minutes (auto-killed if stuck)"
Write-Host "  CPU:         Below-normal — won't slow down your work"
Write-Host "  Silent:      No window, no terminal flash"
Write-Host "  Results:     $ScraperDir\job_tracker.xlsx"
Write-Host "  Logs:        $LogPath"
Write-Host ""
Write-Host "To run manually now:"
Write-Host "  & `"$PythonExe`" `"$ScriptPath`" --quick"
Write-Host ""
Write-Host "To force it to re-run today (delete the stamp):"
Write-Host "  Remove-Item `"$ScraperDir\.last_run_date`" -ErrorAction SilentlyContinue"
Write-Host ""
Write-Host "To uninstall completely:"
Write-Host "  Unregister-ScheduledTask -TaskName $TaskName -Confirm:`$false"
