# run_once_today.ps1  â€”  generated by install_startup_task.ps1
# Ensures the scraper runs at most once per calendar day.

$StampFile  = Join-Path "C:\experiment\auto job search\job_scraper" ".last_run_date"
$PythonExe  = "C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps\python.exe"
$ScriptPath = "C:\experiment\auto job search\job_scraper\main.py"
$Today      = (Get-Date).ToString("yyyy-MM-dd")

# Read last run date
$LastRun = ""
if (Test-Path $StampFile) {
    $LastRun = (Get-Content $StampFile -Raw).Trim()
}

# Already ran today â€” exit silently
if ($LastRun -eq $Today) {
    exit 0
}

# Wait 30 seconds for network to come up after wake/login
Start-Sleep -Seconds 30

# Run the scraper
& $PythonExe $ScriptPath --quick

# Record today's date as the last run date
$Today | Set-Content $StampFile
